apiVersion: v1
kind: Namespace
metadata:
  name: chaos-cpu-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cpu-target
  namespace: chaos-cpu-test
  labels:
    app: cpu-hog-target
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog-target
  template:
    metadata:
      labels:
        app: cpu-hog-target
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
            memory: "100Mi"
          limits:
            cpu: "3000m"  # Highly raised threshold to allow the container runtime to ingest the hog load safely
            memory: "500Mi"
