apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-hog-sa
  namespace: chaos-cpu-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpu-hog-role
  namespace: chaos-cpu-test
rules:
  - apiGroups: ["", "apps", "batch", "litmuschaos.io"]
    resources: 
      - "pods"
      - "jobs"
      - "pods/log"
      - "events"
      - "chaosengines"
      - "chaosresults"
      - "chaosexperiments"
      - "pods/exec"
      - "replicasets"   # <-- Added to let Litmus map the pod tree structure
      - "deployments"  # <-- Added to authorize deployment parent mapping
    verbs: ["create", "list", "get", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpu-hog-role-binding
  namespace: chaos-cpu-test
subjects:
  - kind: ServiceAccount
    name: cpu-hog-sa
    namespace: chaos-cpu-test
roleRef:
  kind: Role
  name: cpu-hog-role
  apiGroup: rbac.authorization.k8s.io
